name: first
on: 
  push:
    branches:
      - '**'
  
  # workflow_dispatch:
  #   inputs:
  #   # we have kind of gated deployment for qa and prod environments, which is manual in gitlab ci/cd, this is an attempt to replicate that.
  #     deploy_env:
  #       type: choice
  #       description: 'Environment to deploy to either qa or prod'
  #       required: true
  #       options:
  #         - qa
  #         - prod
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step one
        run: env | sort
  job2:
    runs-on: windows-latest
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step two
        run: "Get-ChildItem Env: | Sort-Object Name"
  job3:
    runs-on: windows-latest
    needs: job2
    environment: qa
    if: github.ref == 'refs/heads/mai'
    steps:
    - name: step one
      uses: actions/checkout@v2
    - name: step two
      run: "Get-ChildItem Env: | Sort-Object Name"
